x:
	@echo There is no default make target. Try make data or make run.

data: \
    dirs \
    genome.fasta \
    reads.fastq \
    $(DB_DIR)/genome-db.1.bt2 \
    $(SAM_DIR)/genome.sam \
    $(SAM_DIR)/genome.bam

run: cluster

all: clean data run

dirs:
	test -d $(DB_DIR) || mkdir $(DB_DIR)
	test -d $(SAM_DIR) || mkdir $(SAM_DIR)

genome.fasta:
	echo '>genome-1' > $@
	random-nt-sequence.py $(GENOME_LENGTH) >> $@

reads.fastq: genome.fasta
	create-reads.py \
            --count $(READ_COUNT) \
            --meanLength $(MEAN_LENGTH) \
            --sdLength $(SD_LENGTH) \
            --rate $(READ_MUTATION_RATE) < $< > $@

$(DB_DIR)/genome-db.1.bt2: genome.fasta
	bowtie2-build -f --quiet genome.fasta $(DB_DIR)/genome-db

$(SAM_DIR)/genome.sam: $(DB_DIR)/genome-db.1.bt2 reads.fastq
	bowtie2 --quiet --local --xeq --all -U reads.fastq -x $(DB_DIR)/genome-db -S $@

## Nucleotide frequency

# nucleotide-plot.html: genome-bowtie2.sam
# 	significant-base-frequencies.py \
#             --homogeneousCutoff $(HOMOGENEOUS_CUTOFF) --minReads $(MIN_READS) --dropUnmapped \
#             --title 'Single infection<br>Virus genome $(GENOME_LENGTH) nt, $(READ_COUNT) reads (mean length $(MEAN_LENGTH), sd $(SD_LENGTH)), $(READ_MUTATION_RATE) read mutation rate.' \
#             --outfile $@ --samfile $<

## Coverage

# CSL_ARGS := --homogeneousCutoff $(HOMOGENEOUS_CUTOFF) --minReads $(MIN_READS)
# CSL_SCRIPT := $(BIN)/coverage-and-significant-locations.py
# coverage.html: genome-bowtie2.sam
# $(CSL_SCRIPT) --outfile $@ $(CSL_ARGS) --referenceId genome-1 --samfile $<

cluster: dirs $(SAM_DIR)/genome.bam genome.fasta
	$(BIN)/cluster.py \
            --sampleName simulated-sample \
            --alignmentFile $(SAM_DIR)/genome.bam \
            --outputDir $(OUT) \
            --homogeneousCutoff $(HOMOGENEOUS_CUTOFF) \
            --verbose 1 \
            --minReads $(MIN_READS) \
            --maxClusterDist $(CLUSTER_DISTANCE_CUTOFF) \
            --referenceGenome genome.fasta \
            --plotSAM \
            --alternateNucleotideMinFreq $(ALTERNATE_NUCLEOTIDE_MIN_FREQ)

all-reads-plot:
	plot-reads-against-all-references.py \
            --sampleName simulated-sample \
            --samFile $(SAM_DIR)/genome.bam \
	    --outputFile $(OUT)/reads-against-all-references.html

clean:
	rm -f *~ genome.fasta reads.fastq
	rm -fr $(DB_DIR) $(SAM_DIR) $(OUT)
