x:
	@echo There is no default make target. Try make data or make run.

# Products no longer (2024-03-27) included in 'all' target:
#
#     consensus-reads-12-genome-1-samtools-on-cluster.fasta

data: \
    dirs \
    $(DB_DIR)/genome-1-db.1.bt2 \
    $(DB_DIR)/genome-2-db.1.bt2 \
    $(DB_DIR)/genome-12-db.1.bt2 \
    $(SAM_DIR)/reads-1-genome-1.sam \
    $(SAM_DIR)/reads-2-genome-2.sam \
    $(SAM_DIR)/reads-12-genome-12-all.sam \
    $(SAM_DIR)/reads-12-genome-12-all.bam \
    $(SAM_DIR)/reads-12-genome-12-best.sam \
    $(SAM_DIR)/reads-12-genome-12-best.bam \
    $(SAM_DIR)/reads-1-genome-1.stats \
    $(SAM_DIR)/reads-2-genome-2.stats \
    $(SAM_DIR)/reads-12-genome-12-all.stats \
    $(SAM_DIR)/reads-12-genome-12-best.stats

run: cluster all-reads-plot

all: clean data run

other: \
    reads-1-genome-1-coverage-and-significant-locations.html \
    reads-2-genome-2-coverage-and-significant-locations.html \
    reads-12-genome-12-coverage-and-significant-locations.html \
    consensus-reads-12-genome-1-samtools.fasta \
    consensus-reads-12-genome-2-samtools.fasta \
    consensus-12-identity.html \
    reads-12-genome-12-significant-base-frequencies.html \
    reads-12-genome-12-significant-base-frequencies-sorted.html

dirs:
	test -d $(DB_DIR) || mkdir $(DB_DIR)
	test -d $(SAM_DIR) || mkdir $(SAM_DIR)

############################## Genomes and reads
genome-1.fasta genome-2.fasta:
	$(BIN)/create-mid-experiment-data.py \
            --out . \
            --genomeLength $(GENOME_LENGTH) \
            --genome2MutationRate $(GENOME_2_MUTATION_RATE) \
            --genome1ReadMutationRate $(READ_MUTATION_RATE) \
            --meanReadLength $(MEAN_LENGTH) \
            --sdReadLength $(SD_LENGTH) \
            --genome1ReadCount $(READ_COUNT) \
            --force

genome-12.fasta: genome-1.fasta genome-2.fasta
	cat $^ > $@

############################## Bowtie2 databases.
$(DB_DIR)/genome-1-db.1.bt2: genome-1.fasta
	bowtie2-build -f --quiet $< $(DB_DIR)/genome-1-db

$(DB_DIR)/genome-2-db.1.bt2: genome-2.fasta
	bowtie2-build -f --quiet $< $(DB_DIR)/genome-2-db

$(DB_DIR)/genome-12-db.1.bt2: genome-1.fasta genome-2.fasta
	bowtie2-build -f --quiet genome-1.fasta,genome-2.fasta $(DB_DIR)/genome-12-db

############################## Bowtie2 SAM files.
$(SAM_DIR)/reads-1-genome-1.sam: $(DB_DIR)/genome-1-db.1.bt2 reads-1.fastq
	run-bowtie2.py \
            --reference genome-1.fasta \
            --index $(DB_DIR)/genome-1-db \
            --fastq1 reads-1.fastq \
            --bowtie2Args '--xeq --local --very-sensitive-local -N 1' \
            --samtoolsViewArgs '' \
            --verbose \
            --out $@ \
            --force

$(SAM_DIR)/reads-2-genome-2.sam: $(DB_DIR)/genome-2-db.1.bt2 reads-2.fastq
	run-bowtie2.py \
            --reference genome-2.fasta \
            --index $(DB_DIR)/genome-2-db \
            --fastq1 reads-2.fastq \
            --bowtie2Args '--xeq --local --very-sensitive-local -N 1' \
            --samtoolsViewArgs '' \
            --verbose \
            --out $@ \
            --force

$(SAM_DIR)/reads-12-genome-12-all.sam: $(DB_DIR)/genome-12-db.1.bt2 reads-12.fastq
	run-bowtie2.py \
            --reference genome-12.fasta \
            --index $(DB_DIR)/genome-12-db \
            --fastq1 reads-12.fastq \
            --bowtie2Args '--all --xeq --local --very-sensitive-local -N 1' \
            --samtoolsViewArgs '' \
            --verbose \
            --out $@ \
            --force

$(SAM_DIR)/reads-12-genome-12-best.sam: $(DB_DIR)/genome-12-db.1.bt2 reads-12.fastq
	run-bowtie2.py \
            --reference genome-12.fasta \
            --index $(DB_DIR)/genome-12-db \
            --fastq1 reads-12.fastq \
            --bowtie2Args '--xeq --local --very-sensitive-local -N 1' \
            --samtoolsViewArgs '' \
            --verbose \
            --out $@ \
            --force

#################### Coverage and significant locations plots
CSL_ARGS := --homogeneousCutoff $(HOMOGENEOUS_CUTOFF) --minReads $(MIN_READS)

CSL_SCRIPT := $(BIN)/coverage-and-significant-locations.py

reads-12-genome-12-coverage-and-significant-locations.html: $(SAM_DIR)/reads-12-genome-12.sam
	 $(CSL_SCRIPT) --outfile $@ $(CSL_ARGS) --referenceId genome-1 --samfile $<

reads-1-genome-1-coverage-and-significant-locations.html: $(SAM_DIR)/reads-1-genome-1.sam
	$(CSL_SCRIPT) --outfile $@ $(CSL_ARGS) --referenceId genome-1 --samfile $<

reads-2-genome-2-coverage-and-significant-locations.html: $(SAM_DIR)/reads-2-genome-2.sam
	$(CSL_SCRIPT) --outfile $@ $(CSL_ARGS) --referenceId genome-2 --samfile $<


cluster: dirs $(SAM_DIR)/reads-12-genome-12-all.bam genome-12.fasta
	$(BIN)/mid-cluster.py \
            --sampleName simulated-sample \
            --alignmentFile $(SAM_DIR)/reads-12-genome-12-all.bam \
            --outputDir $(OUT) \
            --homogeneousCutoff $(HOMOGENEOUS_CUTOFF) \
            --verbose 1 \
            --minReads $(MIN_READS) \
            --maxClusterDist $(CLUSTER_DISTANCE_CUTOFF) \
            --referenceGenome genome-12.fasta \
            --plotSAM \
            --alternateNucleotideMinFreq $(ALTERNATE_NUCLEOTIDE_MIN_FREQ)

all-reads-plot:
	plot-reads-against-all-references.py \
            --sampleName simulated-sample \
            --samFile $(SAM_DIR)/reads-12-genome-12-best.bam \
	    --outputFile $(OUT)/reads-against-all-references.html


############################## Consensus sequences built with bcftools
consensus-reads-12-genome-1-samtools.fasta: genome-12.fasta $(SAM_DIR)/reads-12-genome-12.bam
	make-consensus.py --reference genome-1.fasta --bam $(SAM_DIR)/reads-12-genome-12.bam | \
            filter-fasta.py --idLambda 'lambda _: "consensus-1-samtools"' --quiet > $@

consensus-reads-12-genome-2-samtools.fasta: genome-12.fasta $(SAM_DIR)/reads-12-genome-12.bam
	make-consensus.py --reference genome-2.fasta --bam $(SAM_DIR)/reads-12-genome-12.bam | \
            filter-fasta.py --idLambda 'lambda _: "consensus-2-samtools"' --quiet > $@

consensus-reads-12-genome-1-samtools-on-cluster.fasta: genome-1.fasta $(CLUSTER_CONSENSUS_BAM)
	make-consensus.py --reference genome-1.fasta --bam $(CLUSTER_CONSENSUS_BAM) \
            --idLambda 'lambda _: "consensus-12-samtools-on-cluster"' > $@

############################## Significant base frequency plots
SBF_ARGS := \
    $(HOMOGENEOUS_CUTOFF) \
    $(MIN_READS) \
    $(GENOME_2_MUTATION_RATE) \
    $(GENOME_LENGTH) \
    $(READ_COUNT) \
    $(MEAN_LENGTH) \
    $(SD_LENGTH) \
    $(READ_MUTATION_RATE)

SBF_SCRIPT := $(BIN)/simulation-significant-base-frequencies.sh

reads-12-genome-12-significant-base-frequencies.html: $(SAM_DIR)/reads-12-genome-12.sam
	$(SBF_SCRIPT) $(SBF_ARGS) $@ $< samtools ''

reads-12-genome-12-significant-base-frequencies-sorted.html: $(SAM_DIR)/reads-12-genome-12.sam
	$(SBF_SCRIPT) $(SBF_ARGS) $@ $< samtools '--sortOn max'

reads-12-genome-12-significant-base-frequencies-mid.html: $(CC_CONSENSUS)
	$(SBF_SCRIPT) $(SBF_ARGS) $@ $< MID ''

reads-12-genome-12-significant-base-frequencies-sorted-mid.html: $(CC_CONSENSUS)
	$(SBF_SCRIPT) $(SBF_ARGS) $@ $< MID '--sortOn max'

############################## FASTA identity table of all consensuses to genome 1

# The order of files below will be the order they appear in the HTML table.
#
# No longer included:
#    $(CC_OUT)/reads-12-genome-12/genome-1/reference-consensus.fasta \
#    $(GREADY_OUT)/reads-12-genome-12/genome-1/reference-consensus.fasta \
#    consensus-reads-12-genome-1-samtools-on-mid.fasta \
#    consensus-reads-12-genome-1-samtools-on-gready.fasta \
#    $(CC_OUT)/reads-12-genome-12/genome-1/non-reference-consensus.fasta
#    consensus-reads-12-genome-1-samtools-on-cluster.fasta \

CONSENSUS_FASTA := \
    genome-1.fasta \
    consensus-reads-12-genome-1-samtools.fasta \
    $(OUT)/reads-12-genome-12/genome-1/reference-consensus.fasta \
    genome-2.fasta \
    consensus-reads-12-genome-2-samtools.fasta

COLOR := \
    --color '0.65 rgb(247,252,240)' \
    --color '0.70 rgb(224,243,219)' \
    --color '0.75 rgb(204,235,197)' \
    --color '0.80 rgb(168,221,181)' \
    --color '0.85 rgb(123,204,196)' \
    --color '0.90 rgb(78,179,211)' \
    --color '0.95 rgb(43,140,190)'

consensus-12-identity.html: $(CONSENSUS_FASTA)
	cat $(CONSENSUS_FASTA) > consensuses.fasta
	fasta-identity-table.py --showGaps --showLengths --footer --removeDescriptions \
            $(COLOR) < consensuses.fasta > $@

clean:
	rm -f *~
	rm -f genome-* LOG
	rm -f *.{fai,fasta,fastq,html,stdout}
	rm -fr $(DB_DIR) $(SAM_DIR) $(OUT)
